#!/bin/bash

# load virtualenv settings
source $HOME/.bash_profile

# virtualenv cleanup
if deactivate 2>&1 >/dev/null; then true; fi
rmvirtualenv set_sshd

mkvirtualenv set_sshd
workon set_sshd

pip install pexpect

