#!/bin/bash

apt-cyg install openssh

## stop sshd process
pid=$(ps -ef | grep sshd | awk '{print $2}') 
[ ${pid} ] && kill -9 ${pid}

## cleanup
if cygrunsrv --query sshd; then
	cygrunsrv --stop sshd
	cygrunsrv --remove sshd    #remove old sshd server
fi
if rm /etc/ssh_* /etc/ssh_config* /etc/sshd_config*; then true; fi

## key-setup
ssh-host-config -y    #this create user: cyg_server

## user/password setup
mkpasswd -l > /etc/passwd

## /etc/passwd cleanup
sort -u /etc/passwd -o /etc/passwd

## add windows firewall rule
cmd /c "netsh advfirewall firewall add rule name="SSHd Server" dir=in action=allow protocol=TCP localport=22"

## start sshd service
cygrunsrv --start sshd

