#!/bin/bash

apt-cyg install openssh

## cleanup
if cygrunsrv --remove sshd; then true; fi    #remove old sshd server
if rm /etc/ssh_* /etc/ssh_config /etc/sshd_config; then true; fi

## key-setup
ssh-host-config -y    #this create user: cyg_server

## user/password setup
mkpasswd -l > /etc/passwd

## adding windows firewall rule
cmd /c "netsh advfirewall firewall add rule name="SSHd Server" dir=in action=allow protocol=TCP localport=22"

## start service
cygrunsrv --start sshd

