#!/bin/bash
set +e

apt-cyg install openssh

## cleanup
if cygrunsrv --remove sshd; then true; fi    #remove old sshd server

## key-setup
ssh-host-config -y    #this create user: cyg_server

## user/password setup
mkpasswd -l > /etc/passwd

## /etc/passwd cleanup
sort -u /etc/passwd -o /etc/passwd

## add windows firewall rule
cmd /c "netsh advfirewall firewall add rule name="SSHd Server" dir=in action=allow protocol=TCP localport=22"

## start sshd service
cygrunsrv --start sshd

